workflows:
  ios-release-build:
    name: iOS Release IPA
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      flutter: stable

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build iOS (release)
        script: |
          flutter build ios --release --no-codesign

      - name: Create IPA
        script: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r Runner.ipa Payload

    artifacts:
      - Runner.ipa
