// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj3LWnUX5FYwsNu8pqoUc0S1NAsOFNePY',
    appId: '1:1062232621076:web:eb342c4b14f71218d2e701',
    messagingSenderId: '1062232621076',
    projectId: 'ready-f3375',
    authDomain: 'ready-f3375.firebaseapp.com',
    storageBucket: 'ready-f3375.firebasestorage.app',
    measurementId: 'G-LMNSWMFNZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMWZ9tFtEy7P0emgjids0zsGH-99DN4Lo',
    appId: '1:1062232621076:android:084f98eb3f469a4ad2e701',
    messagingSenderId: '1062232621076',
    projectId: 'ready-f3375',
    storageBucket: 'ready-f3375.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ6sagLLkMwhZwtN-RCpJCatuB8etOeOo',
    appId: '1:1062232621076:ios:e34aa63da063630cd2e701',
    messagingSenderId: '1062232621076',
    projectId: 'ready-f3375',
    storageBucket: 'ready-f3375.firebasestorage.app',
    iosBundleId: 'com.example.ready',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ6sagLLkMwhZwtN-RCpJCatuB8etOeOo',
    appId: '1:1062232621076:ios:e34aa63da063630cd2e701',
    messagingSenderId: '1062232621076',
    projectId: 'ready-f3375',
    storageBucket: 'ready-f3375.firebasestorage.app',
    iosBundleId: 'com.example.ready',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAj3LWnUX5FYwsNu8pqoUc0S1NAsOFNePY',
    appId: '1:1062232621076:web:acc9883ef4a993bed2e701',
    messagingSenderId: '1062232621076',
    projectId: 'ready-f3375',
    authDomain: 'ready-f3375.firebaseapp.com',
    storageBucket: 'ready-f3375.firebasestorage.app',
    measurementId: 'G-662PPRKBH0',
  );

}